name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: test
      run: |
        echo hello world!
