name: Timer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    type: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo hello world!
